### ISSUE TITLE
CPU support?

### ISSUE THREAD

**Issue by starinspace** [JoeyBallentine/ESRGAN#14]
If I want to try this without CUDA, is it possible to try with CPU and what should I add to the line?

`python upscale.py 4xBox.pth --seamless tile`

**Comment by alsa64** [comment]
Add either `--cpu` or `-c`.
I could have sworn it was in the readme, but apparently not.

**Comment by starinspace** [comment]
--cpu did not work, but -c did.

And I just realized, that "python upscale.py /models/thingie.pth" did not work but "python upscale.py models/thingie.pth" did (I use powershell, don't know if thats why...

Thank you. :D

**Comment by alsa64** [comment]
`/` means it's an absolute path starting from the "root" while `./` or just writing the name of a folder file without the `/` or `./` in front of it is a relative path, starting in the current working directory (for which `.` is the shorthand).

**Comment by alsa64** [comment]
If your issue is resolved, feel free to close it.

**Comment by starinspace** [comment]
It is, thank you. :D
