### ISSUE TITLE
upscale.py gives an error since last commit

### ISSUE THREAD

**Issue by marcoc2** [JoeyBallentine/ESRGAN#16]
I've observed my colab was broken today and them I realized I had to checkout one commit later (9000b43e3acf8709626f45951bb91ace1d983359) here for it to be fixed.

That's the error it gives me

Traceback (most recent call last):
  File "upscale.py", line 20, in <module>
    from utils.architecture.RRDB import RRDBNet as ESRGAN
  File "/content/Colab-ESRGAN/utils/architecture/RRDB.py", line 15, in <module>
    STATE_T = OrderedDict[str, Tensor]
TypeError: 'type' object is not subscriptable

And thats the command:

!cd "/content/Colab-ESRGAN" && python upscale.py 1x_JPEG_00-20.pth --input /content/current_movie/frames --output /content/current_movie/sr

**Comment by JoeyBallentine** [comment]
Any idea what python version your Colab instance is running? This is an issue with older versions of python if I remember correctly. I may have to just get rid of the type hinting if this is gonna be an issue

**Comment by JoeyBallentine** [comment]
@marcoc2 Can you try on the latest commit? Should be fixed now

**Comment by marcoc2** [comment]
I'll try. But the python version on colab is 3.7.12

**Comment by marcoc2** [comment]
Still the same error

**Comment by JoeyBallentine** [comment]
Huh ok.... I guess I just need to remove the type hinting entirely

**Comment by JoeyBallentine** [comment]
I guess try now

**Comment by JoeyBallentine** [comment]
Hello, any update on if it works now or not?

**Comment by marcoc2** [comment]
Just found out by accident that is working now! (Using a notebook I didn't checked out the specific commit hash for the working version)

**Comment by JoeyBallentine** [comment]
Good to hear 👍
