### ISSUE TITLE
Setting "outscale" to 1?

### ISSUE THREAD

**Issue by sharisiri** [joeyballentine/ESRGAN#17]
First off, huge thanks for the effort in putting this together. It's been a pleasure working with the code.

I am chaining a number of different pre-trained models that all have x4 enhancement but I don't need to upscale the image size that much. The final aim is to enhance the image at 4x in total but to get the effects of the different models in a chained manner. Is there a way to set --outscale to 1 as is possible in REAL-ESRGAN?

**Comment by joeyballentine** [comment]
Sorry for not responding sooner. No this isn't possible. However, I probably won't add it because tbh this repo just needs to be rewritten from scratch. Maybe some day. However if you don't mind using a GUI you could do this easily with chaiNNer

**Comment by sharisiri** [comment]
Thanks, appreciate your effort. Really enjoy using this repo.
